import { Characteristics } from "../../../entities/character/types";

export const fixerStatPresets: Record<string, Characteristics> = {
    1: {
        intelligence: 7,
        reflexes: 6,
        agility: 6,
        tech: 3,
        cool: 6,
        will: 6,
        luck: 7,
        movement: 5,
        body: 6,
        empathy: 10,
    },
    2: {
        intelligence: 9,
        reflexes: 5,
        agility: 5,
        tech: 5,
        cool: 6,
        will: 6,
        luck: 10,
        movement: 5,
        body: 5,
        empathy: 10,
    },
    3: {
        intelligence: 7,
        reflexes: 5,
        agility: 5,
        tech: 5,
        cool: 6,
        will: 6,
        luck: 10,
        movement: 5,
        body: 5,
        empathy: 9,
    },
    4: {
        intelligence: 7,
        reflexes: 6,
        agility: 7,
        tech: 7,
        cool: 7,
        will: 7,
        luck: 7,
        movement: 7,
        body: 6,
        empathy: 9,
    },
    5: {
        intelligence: 10,
        reflexes: 5,
        agility: 5,
        tech: 5,
        cool: 5,
        will: 5,
        luck: 10,
        movement: 6,
        body: 5,
        empathy: 9,
    },
    6: {
        intelligence: 9,
        reflexes: 5,
        agility: 5,
        tech: 5,
        cool: 7,
        will: 7,
        luck: 10,
        movement: 7,
        body: 5,
        empathy: 9,
    },
}