import { Characteristics } from "../../../entities/character/types";

export const netRunnerPresets: Record<string, Characteristics> = {
    1: {
        intelligence: 6,
        reflexes:  7,
        agility:  10,
        tech:  7,
        cool:  8,
        will:  4,
        luck:  10,
        movement:  5,
        body:  5,
        empathy:  3,
    },
    2: {
        intelligence: 7,
        reflexes:  10,
        agility:  8,
        tech:  6,
        cool:  10,
        will:  3,
        luck:  10,
        movement:  7,
        body:  6,
        empathy:  4,
    },
    3: {
        intelligence: 7,
        reflexes:  9,
        agility:  10,
        tech:  7,
        cool:  8,
        will:  6,
        luck:  8,
        movement:  7,
        body:  7,
        empathy:  5,
    },
    4: {
        intelligence: 5,
        reflexes:  10,
        agility:  7,
        tech:  7,
        cool:  10,
        will:  4,
        luck:  7,
        movement:  7,
        body:  5,
        empathy:  3,
    },
    5: {
        intelligence: 6,
        reflexes:  9,
        agility:  8,
        tech:  6,
        cool:  8,
        will:  5,
        luck:  8,
        movement:  6,
        body:  5,
        empathy:  6,
    },
    6: {
        intelligence: 5,
        reflexes:  9,
        agility:  7,
        tech:  7,
        cool:  8,
        will:  6,
        luck:  7,
        movement:  6,
        body:  5,
        empathy:  4,
    },
}