import { Characteristics } from "../../../entities/character/types";

export const nomandStatPresets: Record<string, Characteristics> = {
    1: {
        intelligence: 6,
        reflexes:  10,
        agility:  9,
        tech:  4,
        cool:  7,
        will:  9,
        luck:  7,
        movement:  7,
        body:  5,
        empathy:  6,
    },
    2: {
        intelligence: 5,
        reflexes:  9,
        agility:  7,
        tech:  5,
        cool:  9,
        will:  9,
        luck:  9,
        movement:  7,
        body:  7,
        empathy:  3,
    },
    3: {
        intelligence: 6,
        reflexes:  8,
        agility:  8,
        tech:  4,
        cool:  7,
        will:  8,
        luck:  8,
        movement:  5,
        body:  7,
        empathy:  4,
    },
    4: {
        intelligence: 7,
        reflexes:  9,
        agility:  7,
        tech:  5,
        cool:  8,
        will:  8,
        luck:  8,
        movement:  7,
        body:  7,
        empathy:  4,
    },
    5: {
        intelligence: 7,
        reflexes:  10,
        agility:  9,
        tech:  5,
        cool:  7,
        will:  10,
        luck:  10,
        movement:  7,
        body:  7,
        empathy:  4,
    },
    6: {
        intelligence: 6,
        reflexes:  8,
        agility:  9,
        tech:  6,
        cool:  8,
        will:  7,
        luck:  8,
        movement:  7,
        body:  5,
        empathy:  3,
    },
}