import { Characteristics } from "../../../entities/character/types";

export const rockerBoyStatPresets: Record<string, Characteristics> = {
    1: {
        intelligence: 5,
        reflexes: 8,
        agility: 5,
        tech: 4,
        cool: 9,
        will: 8,
        luck: 6,
        movement: 6,
        body: 10,
        empathy: 6,
    },
    2: {
        intelligence: 5,
        reflexes: 10,
        agility: 6,
        tech: 3,
        cool: 9,
        will: 10,
        luck: 6,
        movement: 6,
        body: 10,
        empathy: 4,
    },
    3: {
        intelligence: 6,
        reflexes: 10,
        agility: 5,
        tech: 3,
        cool: 9,
        will: 10,
        luck: 7,
        movement: 5,
        body: 8,
        empathy: 5,
    },
    4: {
        intelligence: 6,
        reflexes: 9,
        agility: 5,
        tech: 6,
        cool: 9,
        will: 9,
        luck: 5,
        movement: 6,
        body: 8,
        empathy: 4,
    },
    5: {
        intelligence: 5,
        reflexes: 10,
        agility: 6,
        tech: 3,
        cool: 10,
        will: 10,
        luck: 6,
        movement: 6,
        body: 8,
        empathy: 4,
    },
    6: {
        intelligence: 6,
        reflexes: 10,
        agility: 7,
        tech: 4,
        cool: 8,
        will: 10,
        luck: 5,
        movement: 7,
        body: 9,
        empathy: 5,
    },
};