import { Characteristics } from '../../../entities/character/types';

export const techStatPresets: Record<string, Characteristics> = {
    1: {
        intelligence: 10,
        reflexes:  10,
        agility:  5,
        tech:  9,
        cool:  3,
        will:  5,
        luck:  7,
        movement:  6,
        body:  5,
        empathy:  6,
    },
    2: {
        intelligence: 10,
        reflexes: 7,
        agility: 6,
        tech: 9,
        cool: 3,
        will: 5,
        luck: 5,
        movement: 5,
        body: 6,
        empathy: 6,
    },
    3: {
        intelligence: 10,
        reflexes: 7,
        agility: 5,
        tech: 10,
        cool: 4,
        will: 3,
        luck: 7,
        movement: 5,
        body: 7,
        empathy: 6,
    },
    4: {
        intelligence: 8,
        reflexes: 8,
        agility: 5,
        tech: 10,
        cool: 4,
        will: 4,
        luck: 7,
        movement: 6,
        body: 5,
        empathy: 5,
    },
    5: {
        intelligence: 7,
        reflexes: 7,
        agility: 7,
        tech: 9,
        cool: 4,
        will: 3,
        luck: 6,
        movement: 6,
        body: 6,
        empathy: 7,
    },
    6: {
        intelligence: 10,
        reflexes: 10,
        agility: 7,
        tech: 8,
        cool: 4,
        will: 5,
        luck: 6,
        movement: 6,
        body: 7,
        empathy: 6,
    },
}